//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyProduct("DotNetty")]
[assembly: AssemblyVersion("0.4.8")]
[assembly: AssemblyFileVersion("0.4.8")]
[assembly: AssemblyCopyright("(c) Microsoft 2015 - 2018")]

