// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("DotNetty")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015")]
[assembly: AssemblyVersionAttribute("0.1.3")]
[assembly: AssemblyFileVersionAttribute("0.1.3")]

