// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("DotNetty")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015")]
[assembly: AssemblyKeyFileAttribute("")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyVersionAttribute("0.2.3")]
[assembly: AssemblyFileVersionAttribute("0.2.3")]
