// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("DotNetty")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015")]
[assembly: AssemblyVersionAttribute("0.1.2.0")]
[assembly: AssemblyFileVersionAttribute("0.1.2.0")]
